name: Run dailyGameGenerator

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run script
      run: node dailyGameGenerator.js
