name: Run dailyGameGenerator

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
            token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Execute DailyGameGenerator script
      run: ruby scheduledTasks/daily_game_generator.rb

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update JSON file" || exit 0
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/LeviGreen/master-mind.git
        git push